### ISSUE TITLE
I cloned the code but I m having an error on 'decodeTileContentDescription' module

### ISSUE THREAD

**Issue by mmuhire** [iTwin/grouping-and-mapping-sample-app#23]
I cloned the code, 
but for some reason, I am getting an error when I start the app. The program cannot find the 'decodeTileContentDescription' module.
How can I resolve this issue?
I copied a portion of the error below.

ERROR in ./node_modules/@itwin/core-frontend/lib/esm/tile/ImdlReader.js 170:16-44
export 'decodeTileContentDescription' (imported as 'decodeTileContentDescription') was not found in '@itwin/core-common'

**Comment by Ellord207** [comment]
I'm not able to reproduce on my machine and I'm not sure what could be causing this.

I would suggest cleaning your node_modules directory and attempting another install.

Something else you could try is to use the `upgrade-4x` branch.  Assuming you are following the course Grouping and Mapping accreditation videos, there should some UI differences from the video but is fully functional otherwise.  Again, be sure to delete your node_modules before trying the new branch.

**Comment by mmuhire** [comment]
Thank you so much. It is working now. I also noticed that I had not changed env.template to env. when I added the ID information
